# -*- coding: utf-8 -*-
{
    "name": """Facturación Electrónica para Chile\
    """,
    'version': '11.0.0.0.0',
    'category': 'Localization/Chile',
    'sequence': 12,
    'author':  'Daniel Santibáñez Polanco, Cooperativa OdooCoop',
    'website': 'https://globalresponse.cl',
    'license': 'AGPL-3',
    'summary': '',
    'description': """
Facturación Electrónica para Chile.
""",
    'depends': [
            'base',
            'account',
            'purchase',
            'sale',
            'l10n_cl_chart_of_account',
            'report_xlsx',
        ],
    'external_dependencies': {
        'python': [
            'xmltodict',
            'dicttoxml',
            'pdf417gen',
            'base64',
            'hashlib',
            'cchardet',
            'suds',
            'urllib3',
            'signxml',
            'ast',
            'pysftp',
            'num2words',
            'xlsxwriter',
            'io',
        ]
    },
    'data': [
            'views/sii_menuitem.xml',
            'views/company_signature_tab.xml',
            'views/invoice_view.xml',
            'views/company_view.xml',
            'views/consumo_folios.xml',
            'views/caf.xml',
            'views/export.xml',
            'views/invoice_view.xml',
            'views/layout.xml',
            'views/libro_compra_venta.xml',
            'views/libro_honorarios.xml',
            'views/mail_dte.xml',
            'views/partner_activities.xml',
            'views/payment_t_view.xml',
            'views/res_company.xml',
            'views/res_partner.xml',
            'views/res_state_view.xml',
            'views/sii_activity_description.xml',
            'views/sii_cola_envio.xml',
            'views/sii_regional_offices_view.xml',
            'views/user_signature_tab.xml',
            'wizard/masive_send_dte.xml',
            'wizard/masive_dte_process.xml',
            'wizard/upload_xml.xml',
            'wizard/validar.xml',
            'data/sequence.xml',
            'data/product.xml',
            #'data/cron.xml',
            'data/partner.activities.csv',
            'data/counties_data.xml',
            'data/sii.regional.offices.csv',
            'security/state_manager.xml',
            'security/ir.model.access.csv',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
