# -*- coding: utf-8 -*-
from . import account_tax
from . import account
from . import caf
from . import company_signature_key
from . import company
from . import consumo_folios
from . import country
from . import currency
#from . import export
from . import honorarios
from . import invoice
from . import libro
from . import mail
from . import partner_activities
from . import payment_term
from . import res_partner
from . import res_state_city
from . import res_state_region
from . import res_state
from . import sale_order
from . import sii_activity_description
from . import sii_cola_envio
from . import sii_regional_offices
from . import sii
from . import user_signature_key
from . import global_descuento_recargo
from . import res_config_settings
